name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    -steps:
      name: setup
      uses: actions/checkout@v2
  Test:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: test
        run: ci/unit-test-app.sh
  Build:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - name: builder
      run: ci/build-app.sh
    - name: uploader 
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .