name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: Upload Repo
          path: .