###
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: setup
        uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Test:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      
  Build:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: builder
      run: chmod +x ci/build-app.sh && ci/build-app.sh
    - name: uploader 
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .
  Docker-image:
    needs: [Test, Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - run: chmod +x ci/build-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/build-docker.sh
      - run: chmod +x ci/push-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/push-docker.sh
  Component-test:
    needs: Docker-image
    runs-on: [self-hosted]
    container: gradle:6-jdk11
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - run: curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)"  -o /usr/local/bin/docker-compose && mv /usr/local/bin/docker-compose /usr/bin/docker-compose && chmod +x /usr/bin/docker-compose
      - run: chmod +x ci/component-test.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ci/component-test.sh