name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: uses-step
        uses: actions/checkout@v2
      - name: run-step
        run: ../../ci/build-app.sh